name: ci-nodej-s-workflow
on:
  pull_request:
    branchs:
      - develop
      
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [17,18]
    steps:
      - uses: actions/checkout@v2 # pega os arquivos que acabou de subir e joga pra maquina ubuntu
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test
      - run: npm run start