name: ci-nodej-s-workflow
on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # pega os arquivos que acabou de subir e joga pra maquina ubuntu
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
      - run: npm run start