name: ci-nodej-s-workflow
on:
  pull_request:
    branchs:
      - develop
      
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [17,18]
    steps:
      - uses: actions/checkout@v2 # pega os arquivos que acabou de subir e joga pra maquina ubuntu
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test
      - run: npm run start

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: adrianohardtke/fc-ci-node:latest